#!/bin/bash
PWD=`pwd`
SOURCE="$PWD/src/*.pas"
LIB="$PWD/lib"
DEST="$PWD/docs"
TITLE="Binky Boink"
DESC="Lib and visualizer for BOINC Client"


pasdoc -D FPC -D LINUX -D UNIX \
   -I "$LIB"\
   -T "$TITLE"\
   -N "$DESC"\
   -O html\
   -E "$DEST"\
   -L en\
   --staronly\
   --write-uses-list\
   --link-look=full\
   --use-tipue-search\
   --auto-link\
   "$SOURCE"
